#!/usr/bin/env python

import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
import tf2_ros
from math import pi
from std_msgs.msg import String
from std_srvs.srv import Empty, EmptyResponse
from moveit_commander.conversions import pose_to_list
from std_msgs.msg   import Float32,Float64

class Control:

    def __init__(self):
        """
        Initialize and setup the Motion Planning Scence
        """
        moveit_commander.roscpp_initialize(sys.argv)
        self.robot = moveit_commander.RobotCommander()
        self.scene = moveit_commander.PlanningSceneInterface()
        self.broadcaster = tf2_ros.TransformBroadcaster()

        self.ysub = rospy.Subscriber("object_y", Float32 ,self.y_callback)
        self.xsub = rospy.Subscriber("object_x", Float32 ,self.x_callback)
        self.Tsub = rospy.Subscriber("highest_T_detected", Float32, self.T_callback)

        # /hdt_arm/pincer_joint_position_controller/command
        self.pincer_pub = rospy.Publisher("/hdt_arm/pincer_joint_position_controller/command", Float64,queue_size=10)
    
        self.service_ready = rospy.Service("ready", Empty, self.ready)
        self.service_grab_ready = rospy.Service("grab_ready",Empty,self.grab_ready)
        self.service_search = rospy.Service("search", Empty, self.search)
        self.service_locate = rospy.Service("locate", Empty, self.locate)
        self.service_press = rospy.Service("press", Empty, self.press)
        self.service_open = rospy.Service("open", Empty, self.open)
        self.service_grab = rospy.Service("grab", Empty, self.grab)

        group_name = 'arm'
        self.group = moveit_commander.MoveGroupCommander(group_name)

        pincer_group_name = 'pincer'
        self.pincer_group = moveit_commander.MoveGroupCommander(pincer_group_name)

        self.scene = moveit_commander.PlanningSceneInterface()
        display_trajectory_publisher = rospy.Publisher("move_group/display_planned_path", moveit_msgs.msg.DisplayTrajectory, queue_size=20)
        self.display_trajectory_publisher = display_trajectory_publisher

        rospy.init_node('arm_control', anonymous=True)
        self.rate = rospy.Rate(120)

        planning_frame = self.group.get_planning_frame()
        print("============ Reference frame: %s" % planning_frame)
        eef_link = self.group.get_end_effector_link()
        print("============ End effector: %s" % eef_link)
        group_names = self.robot.get_group_names()
        print("============ Robot Groups:", self.robot.get_group_names())
        print("============ Printing robot state")
        print(self.robot.get_current_state())
        print("")


        ready = rospy.ServiceProxy("ready", Empty)
        grab_ready = rospy.ServiceProxy("grab_ready",Empty)
        search = rospy.ServiceProxy("search",Empty)
        locate = rospy.ServiceProxy("locate",Empty)
        press = rospy.ServiceProxy("press",Empty)
        p_open = rospy.ServiceProxy("open",Empty)
        p_grab = rospy.ServiceProxy("grab",Empty)

        fire_status = 0

        global grab_angle
        grab_angle = 0.23
        
        self.setup_env()
        rospy.sleep(1)
        grab_ready()
       
    def y_callback(self,data):
        global y
        y = data.data
        # rospy.loginfo("I heard %f",y)
    def x_callback(self,data):
        global x
        x = data.data
        # rospy.loginfo("I heard %f",y)

    def T_callback(self,data):
        global T_max
        T_max = data.data

    def press(self,val):
        
        self.pincer_pub.publish(0.1)

        return []

    def grab(self,val):
       
        self.pincer_pub.publish(0.8)
        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = -55*pi/180
        self.joint_goal[1] = -20*pi/180
        self.joint_goal[2] = 4*pi/180
        self.joint_goal[3] = -84*pi/180
        self.joint_goal[4] = -75*pi/180
        self.joint_goal[5] = 109*pi/180
        self.group.go(self.joint_goal, wait=True)
        # self.group.stop()
        self.joint_goal[0] = -23*pi/180
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        self.pincer_pub.publish(grab_angle)

        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = 0
        self.joint_goal[1] = 0
        self.joint_goal[2] = 0
        self.joint_goal[3] = - 90*pi/180
        self.joint_goal[4] = -85*pi/180
        self.joint_goal[5] = 95*pi/180
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        
        return []

    def open(self,val):

        self.pincer_pub.publish(0.4)

        return []

    def locate(self,val):

        self.pincer_pub.publish(grab_angle)
        self.joint_goal = fire_joint 
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        return []

    
    def look_down(self):
        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = 0
        self.joint_goal[1] = 0
        self.joint_goal[2] = 0
        self.joint_goal[3] = - 90*pi/180
        self.joint_goal[4] = -85*pi/180
        self.joint_goal[5] = 75*pi/180
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        return []

    def search(self,val):
        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = 0
        self.joint_goal[1] = 0
        self.joint_goal[2] = 0
        self.joint_goal[3] = - 90*pi/180
        self.joint_goal[4] = -85*pi/180
        self.joint_goal[5] = 70*pi/180
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        self.pincer_pub.publish(grab_angle)
        self.joint_goal = self.group.get_current_joint_values()
        
        j1 = -0.2
        
        while T_max < 70.0:
    
            self.joint_goal[0] = j1
            self.joint_goal[5] = 110*pi/180
            self.group.go(self.joint_goal, wait=True)
            self.joint_goal[5] = 70*pi/180
            self.group.go(self.joint_goal, wait=True)
            j1 = j1 - 0.4

         
        self.group.stop()

        # Resolution is 640 X 480
        half_x = 640/2 # this is half of the resolution for x
        half_y = 480/2 # this is half of the resouution for y
        movement = 0.005 * pi

        # 2D x-control (pose.y control for robot)

        # if the location of the fire is on the right side of the screen
        if x > half_x:
            while x > half_x:
                self.joint_goal = self.group.get_current_joint_values()
                self.joint_goal[0] = self.joint_goal[0] - movement
                self.group.go(self.joint_goal, wait=True)
               

        if x < half_x:
            while x < half_x:
                self.joint_goal = self.group.get_current_joint_values()
                self.joint_goal[0] = self.joint_goal[0] + movement
                self.group.go(self.joint_goal, wait=True)

        if y > half_y:
            while y > half_y:
                self.joint_goal = self.group.get_current_joint_values()
                self.joint_goal[2] = self.joint_goal[2] - movement
                self.group.go(self.joint_goal, wait=True)
        
        if y < half_y:
            while y < half_y:
                self.joint_goal = self.group.get_current_joint_values()
                self.joint_goal[2] = self.joint_goal[2] + movement
                self.group.go(self.joint_goal, wait=True)

        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = self.joint_goal[0] - 0.05*pi
        self.group.go(self.joint_goal, wait=True)

        self.group.stop()

        global fire_joint
        fire_joint = self.group.get_current_joint_values()

        return []
   
    def move(self):
        self.pose_goal = geometry_msgs.msg.Pose()
        self.pose_goal.orientation.w = 1.0
        self.pose_goal.position.x = 0.4
        self.pose_goal.position.y = 0.1
        self.pose_goal.position.z = 0.4
        self.group.set_pose_target(self.pose_goal)
        self.plan = self.group.go(wait=True)
        self.group.stop()
        self.group.clear_pose_targets()


    def ready(self,val):

        """
        Service can be called by rosservice
        Sends the arm back to its 'ready' position
        """
        
        self.group.set_named_target("ready")
        self.group.go()
        return []


    def grab_ready(self,val):
        self.joint_goal = self.group.get_current_joint_values()
        self.joint_goal[0] = 0
        self.joint_goal[1] = 0
        self.joint_goal[2] = 0
        self.joint_goal[3] = - 90*pi/180
        self.joint_goal[4] = -85*pi/180
        self.joint_goal[5] = 95*pi/180
        self.group.go(self.joint_goal, wait=True)
        self.group.stop()
        self.group.clear_pose_targets()
        self.pincer_pub.publish(0.4)
        return []
    
    def setup_env(self):
        # Table
        self.table_pose = geometry_msgs.msg.PoseStamped()
        self.table_pose.header.frame_id = 'base_link'
        self.table_pose.pose.position.x = 0.
        self.table_pose.pose.position.y = 0.
        self.table_pose.pose.position.z = -0.01/2
        self.scene.add_cylinder("table", self.table_pose, 0.01, 1)

        # Power Supply 
        self.box_pose = geometry_msgs.msg.PoseStamped()
        self.box_pose.header.frame_id = 'base_link'
        self.box_pose.pose.position.x = 0
        self.box_pose.pose.position.y = 0.15
        self.box_pose.pose.position.z = 0.15/4
        self.scene.add_box("obstacle", self.box_pose, size=(grab_angle/2, 0.15/2, 0.15/2))


        # Cylinder
        self.cylinder_pose = geometry_msgs.msg.PoseStamped()
        self.cylinder_pose.header.frame_id = 'base_link'
        self.cylinder_pose.pose.position.x = 0.5
        self.cylinder_pose.pose.position.y = 0
        self.cylinder_pose.pose.position.z = 0.15
        # self.scene.add_cylinder("fire extinguisher", self.cylinder_pose, 0.3, 0.04)


if __name__ == "__main__":
  
    Control()
    rospy.spin()
        